# Generated by Django 2.2.6 on 2019-10-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('service_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=20)),
                ('plan_name', models.CharField(max_length=20)),
                ('fee_per_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mail_address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=20)),
            ],
        ),
    ]
